### PR TITLE
Pagination UI 

### PR DESCRIPTION
**Pull request by Justinnn07**
> 🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master**
- [x] Make sure no conflicts are present in the code, if so please resolve it(_Tip: Always fetch upstream_)
- [x] Your Commit messages should make sense.
- [x] Don't push your package.lock.json as this project uses yarn.lock already.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Describe your changes

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Made the pagination responsive
 
- **What is the current behavior?** (You can also link to an open issue here)
- resolves #118 

- **What is the new behavior (if this is a feature change)?**
- I couldn't use material-ui pagination, I use the library named react-paginate

- **Other Information**:

❤️ Thank you!

### CODE REVIEW

**Comment by Justinnn07** [comment]
@stephin007 I could use material-ui for this, Please have a look  and let me know your reviews

**Comment by stephin007** [comment]
so @Justinnn07  what did you use for pagination if you did not use material UI

**Comment by Justinnn07** [comment]
> so @Justinnn07 what did you use for pagination if you did not use material UI

CSS!

**Comment by stephin007** [comment]
you added a new package?
please add that in the PR description!

Will review soon!

**Comment by stephin007** [comment]
@Justinnn07 this looks cool, just need some CSS tweaks!

**Comment by stephin007** [comment]
Following is needed to be fixed:
- Can we use symbols instead of next and prev.
- Can we use material pagination look for this instead of css, as we are migrating to MATERIAL UI.

@Justinnn07 ^^

**Pull request closed without merging**
