### PR TITLE
Feature: Add Test Cases

### LINKED ISSUE #99: Add Test Cases
Please refer this documentation for better explanation:

https://dzone.com/articles/unit-testing-in-reactjs-using-jest-and-enzyme

### PR DESCRIPTION
**Pull request by kunalkumar007**
This branch adds a test feature to the Application.

**Major Change**:- downgraded React v17 to React v16 because adds extra functionality for React App.

**Added Packages**:- 
- Jest
- Enzyme
- react-test-renderer
- enzyme-adapter-react-16
- enzyme-to-json

Closes #99

### CODE REVIEW

**Comment by stephin007** [comment]
@wise-introvert can you please review this PR!

**Comment by wise-introvert** [comment]
@kunalkumar007 what does downgrading to v16 bring to the table?

**Comment by stephin007** [comment]
@kunalkumar007 it would be great if you could update the documentation about how to run the tests in our local envs.

Then we can merge your request:🎉

Thanks❤️

**Comment by wise-introvert** [comment]
@kunalkumar007, adding to @stephin007's comment above, please also add instructions to update snapshots ( for UI changes )

**Comment by kunalkumar007** [comment]
**I have updated the docs.**
- In **Contributing.md**, I have added the instructions for running the test, snapshots, and the coverage report.
-  In **Package.json**, I have updated the scripts for running the test, snapshots, and coverage report.

**Review by stephin007 — APPROVED** [review]
Approved by @wise-introvert

**Comment by stephin007** [comment]
hey @kunalkumar007 Great work, your PR is now merged.
Would you like to join our core team to help to develop more feature to this project.
let me know your thoughts 😀

Thanks ❣️

**Comment by kunalkumar007** [comment]
> hey @kunalkumar007 Great work, your PR is now merged.
> Would you like to join our core team to help to develop more feature to this project.
> let me know your thoughts 😀
> 
> Thanks ❣️

I will be happy to join the team to develop awesome projects like this one.

**Comment by kunalkumar007** [comment]
I wìll be happy to join the team. Lookijg forward to working with you.

**Comment by stephin007** [comment]
Awesome @kunalkumar007 , As we want more bright minds we would love to have you on our team!

Sending you the telegram invite link: https://t.me/joinchat/5WNdVxHJ9YRjN2Fl

**Comment by stephin007** [comment]
@kunalkumar007 can you please update when will you be joining?

**Comment by kunalkumar007** [comment]
I joined it.

**Pull request merged**
