### PR TITLE
Feature: Add Whole world Vaccine Information

### PR DESCRIPTION
**Pull request by stephin007**
> 🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master**
- [x] Make sure no conflicts are present in the code, if so please resolve it(_Tip: Always fetch upstream_)
- [x] Your Commit messages should make sense.
- [x] Don't push your package.lock.json as this project uses yarn.lock already.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Describe your changes

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
New Feature

- **What is the current behavior?** (You can also link to an open issue here)
No information related to COVID-19 around the world

- **What is the new behavior (if this is a feature change)?**
New Page added

- **Does this PR introduce a breaking change?** (i.e changes that may require users to update/refactor existing istances of the application)
No

- **Other Information**:
This PR will be start to the issue 116

❤️ Thank you!

### CODE REVIEW

**Comment by stephin007** [comment]
@Justinnn07 please review this, but please dont merge!
Let me know your thoughts

**Review by Justinnn07 — COMMENTED** [review]
Nice work @stephin007 💥💥

**Comment by stephin007** [comment]
@Justinnn07 please review changes again, please dont merge!

I am asking this because, it wont be a burden for you to check all the files at one!

Apologies for any inconvenience

**Comment by Justinnn07** [comment]
> @Justinnn07 please review changes again, please dont merge!
> 
> I am asking this because, it wont be a burden for you to check all the files at one!
> 
> Apologies for any inconvenience

sure @stephin007

**Review by Justinnn07 — COMMENTED** [review]
Nicee work! 🚀🚀 @stephin007

**Comment by stephin007** [comment]
@Justinnn07 Please review again! let me know your thoughts. content is not responsive yet!

**Review by Justinnn07 — COMMENTED** [review]
Nice work! 💯 @stephin007 

Please do look color combination for the same!

**Comment by stephin007** [comment]
I can make all the paper headings the same color, because having seperate colors will make it look weird.

Can you let me know what color should we use for the paper titles ? @Justinnn07

**Comment by Justinnn07** [comment]
> I can make all the paper headings the same color, because having seperate colors will make it look weird.
> 
> Can you let me know what color should we use for the paper titles ? @Justinnn07

image
How's this color? @stephin007

**Comment by stephin007** [comment]
@Justinnn07 Can you please review this PR for the final time, in my opinion we Should merge this PR as an initial look for the new page added to website and also not close the issue as many enhancements are gonna come to this page

rest for further enhancements to this issue i  will raise other PRs!

**Review by Justinnn07 — APPROVED** [review]
LGTM! 💥 @stephin007

**Pull request merged**
