### PR TITLE
Feat: marker component to pinpoint location on the map

### LINKED ISSUE #107: Marker component to indicate location
Create a marker component to help indicate the exact location of the respective vaccine center in the single-vaccine-card component.

### PR DESCRIPTION
**Pull request by wise-introvert**
> 🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master**
- [x] Your Commit messages should make sense.
- [x] Don't push your package.lock.json as this project uses yarn.lock already.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Describe your changes

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  - feat
- **What is the current behavior?** (You can also link to an open issue here)
  - no marker
- **What is the new behavior (if this is a feature change)?**
  - marker icon on each map
- **Does this PR introduce a breaking change?** (i.e changes that may require users to update/refactor existing istances of the application)
  - no
- **Other Information**:
  - closes #107 

### Screenshots
image

❤️ Thank you!

### CODE REVIEW

**Comment by stephin007** [comment]
Some unused vars @wise-introvert , can you please check the below screenshot.
image

**Comment by Justinnn07** [comment]
@wise-introvert please pull the latest changes and fix these conflicts!

thanks

**Review by stephin007 — APPROVED** [review]
LGTM @wise-introvert 🔥

**Comment by stephin007** [comment]
@wise-introvert we have one query regarding the token!
in the Map/index,js we are not seeing the token which is getting passed to MAPBOX.

I have passed the token but i am not able to find the process.env.REACT_APP_MAPBOX_ACCESS_TOKEN in the whole code system!

Can you please tell what changes have you done? Do we need token anymore?

It would be great if you tell about this soon as we might need to change the documentation.

**Comment by wise-introvert** [comment]
In order to better implement the marker functionality, I switched to [react-map-gl](https://npmjs.com/react-map-gl). Unlike the native library that I was using earlier, this library automatically fetches the `REACT_APP_MAPBOX_ACCESS_TOKEN` from the `.env` file, removing any need to mention the key in the codebase.

**Comment by stephin007** [comment]
Nice @wise-introvert , thanks for the update! It would be great if you check other issues as well!

If you are willing i would love to have you in the core team! Let me know i ll share you the telegram join link.

❤️

**Comment by wise-introvert** [comment]
I'll only be able to work on this project on weekends and if that works for you then I would love to be a part of the core team!

**Comment by stephin007** [comment]
Awesome to hear that @wise-introvert , Please join this link: https://t.me/joinchat/r8plTmfSLg41YTBl

**Comment by wise-introvert** [comment]
@stephin007 the link seems to be broken. Can you please send me a new one?

**Comment by stephin007** [comment]
try this: https://t.me/joinchat/5WNdVxHJ9YRjN2Fl

**Pull request merged**
