### PR TITLE
ABOUT PAGE REVAMP

### PR DESCRIPTION
**Pull request by stephin007**
> 🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master**
- [x] Make sure no conflicts are present in the code, if so please resolve it(_Tip: Always fetch upstream_)
- [x] Your Commit messages should make sense.
- [x] Don't push your package.lock.json as this project uses yarn.lock already.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Describe your changes

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Enhancement 

- **What is the current behavior?** (You can also link to an open issue here).
About Page was empty earlier with very less information

- **What is the new behavior (if this is a feature change)?**
- Added list of contributors, right now this PR is in progress , will add proper information of the app in  the about page.

### 🚨 NOTE FOR THE REVIEWER :🚨 
This PR is
- [ ] not yet dark mode compatible
- [x] not mobile responsive.
- [ ] incomplete, will add more information

- **Does this PR introduce a breaking change?** (i.e changes that may require users to update/refactor existing istances of the application)
Nil, No packages were added only 2 files were changed which are :
1. About.js
2.  about.css

**Other Information**:
NONE

❤️ Thank you!

### CODE REVIEW

**Review by Justinnn07 — COMMENTED** [review]
Nice work @stephin007

**Comment by stephin007** [comment]
@Justinnn07 Please review this, can you please merge this PR,  ill raise another PR to make About Page dark mode compatible.

Let me know if there is anything which needs to be changed please let me know

**Comment by Justinnn07** [comment]
> @Justinnn07 Please review this, can you please merge this PR,  ill raise another PR to make About Page dark mode compatible.
> 
> Let me know if there is anything which needs to be changed please let me know

Sure! 💯

**Review by Justinnn07 — APPROVED** [review]
Nice work @stephin007

**Pull request merged**
