### PR TITLE
Finished with pagination 

### PR DESCRIPTION
**Pull request by Justinnn07**

### CODE REVIEW

**Comment by stephin007** [comment]
@Justinnn07 the pagination looks awesome , but few things to consider!

- can you change the look of the pagination number to some what like this: << 1 2 >> rather showing 1 2 3 4 5.
 - Add pagination at the bottom of the list, and reduce the count of cards per page , such that User will be forced to go down and checkout for more!
 
 Please look into the above, appreciate the efforts buddy!

**Comment by Justinnn07** [comment]
Sure! @stephin007

**Review by stephin007 — CHANGES_REQUESTED** [review]
Changes looks good but please look into the comments i have added

**Comment by Justinnn07** [comment]
Done! @stephin007

**Comment by stephin007** [comment]
Not quite what i asked for! @Justinnn07 😅 

right now if i click on the arrows, i am not able to understand on which page am i? 
Also if you are giving arrows, there is no point of showing the numbers

You understand my point?

**Comment by Justinnn07** [comment]
I am resolving conflicts!

**Pull request closed without merging**
