### PR TITLE
Enhancement: Enhanced the look for word COVID Info

### PR DESCRIPTION
**Pull request by stephin007**
> 🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master**
- [x] Make sure no conflicts are present in the code, if so please resolve it(_Tip: Always fetch upstream_)
- [x] Your Commit messages should make sense.
- [x] Don't push your package.lock.json as this project uses yarn.lock already.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Describe your changes

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Enhancement

- **What is the current behavior?** (You can also link to an open issue here)
Right now user can only see data from world, added a feature now the user to select about what they want to checkout

- **What is the new behavior (if this is a feature change)?**
Now, user can select the data they want to checkout similar to vaccine page.

- **Does this PR introduce a breaking change?** (i.e changes that may require users to update/refactor existing istances of the application)
NONE

- **Other Information**:
Enhancement to #116 

❤️ Thank you!

### CODE REVIEW

**Comment by stephin007** [comment]
@Justinnn07 dont merge the request as tesing is doing on but please review the changes.

Also, dont close the issue as well!

**Comment by stephin007** [comment]
@Justinnn07 more options is yet to be added in the select options, for which a seperate PR will be raised!

**Comment by Justinnn07** [comment]
@stephin007 please remove loading from the "India" tab! Rest changes looks good! 💯💥

**Comment by stephin007** [comment]
@Justinnn07 the fix is done please review!

**Review by Justinnn07 — APPROVED** [review]
Nice work! 💥💯 @stephin007

**Pull request merged**
