### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by Justinnn07**
I hope this works fine? @stephin007

### CODE REVIEW

**Comment by stephin007** [comment]
Please update the title of the PR. @Justinnn07

**Comment by Justinnn07** [comment]
> Please update the title of the PR. @Justinnn07

done 💯

**Comment by stephin007** [comment]
@Justinnn07 can you please add the pagination to the bottom please , as i said yesterday!

**Review by stephin007 — APPROVED** [review]
Nice work

**Pull request merged**
