### PR TITLE
FilterIssue

### PR DESCRIPTION
**Pull request by himanshujasuja1040**
> 🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master** :yes
- [x] Make sure no conflicts are present in the code, if so please resolve it(_Tip: Always fetch upstream_) :  No conflict
- [x] Your Commit messages should make sense.   : Yup
- [x] Don't push your package.lock.json as this project uses yarn.lock already. :ok
- [x] Check your code additions will fail neither code linting checks nor unit test. :ok

### Describe your changes

- **What kind of change does this PR introduce?** : (Filter Bug Fixed)

- **What is the current behavior?** : (Not Have any Filter component)

- **What is the new behavior (if this is a feature change)?** : (Added a Filter Component for filtering vaccine)

- **Does this PR introduce a breaking change?** :(Nope)

- **Other Information**: (Nope)

❤️ Thank you!

### CODE REVIEW

**Comment by himanshujasuja1040** [comment]
@Justinnn07

**Comment by stephin007** [comment]
Complete the PR template @himanshujasuja1040

**Comment by stephin007** [comment]
@himanshujasuja1040 Add no data found component, when no data is found according to the added filters.

**Comment by Justinnn07** [comment]
@himanshujasuja1040 great work! 
Few points to be noted:-

1. Please remove the pagination .. 
2. If the filtered array is 0, please show the no data found component .. 
3. The Fare filter is not working .. 

Thanks

**Comment by Justinnn07** [comment]
@himanshujasuja1040 any update?

**Comment by stephin007** [comment]
Outdated PR,  closing it!

**Pull request closed without merging**
