### PR TITLE
added a loading component 

### PR DESCRIPTION
**Pull request by afif1400**
This pull request resolves the issue #97, added a loading component which is a circular progress bar from material-ui.

### CODE REVIEW

**Comment by stephin007** [comment]
@afif1400 please answer the questions which was given in the PR TEmplate, that way i ll be able to understand what changes you have made!

Then only ill be able ti review and merge.

Thanks 🙏🏾

**Comment by stephin007** [comment]
Also, there are lot of linting issues, please revert back your commits as it has created un necessary spaces in various files. As shown below, please revert back to original spacing except in the file you add the loading feature.



image

**Comment by afif1400** [comment]
> @afif1400 please answer the questions which was given in the PR TEmplate, that way i ll be able to understand what changes you have made!
> 
> Then only ill be able ti review and merge.
> 
> Thanks 🙏🏾

Yeah I'll do that

**Comment by afif1400** [comment]
> Also, there are lot of linting issues, please revert back your commits as it has created un necessary spaces in various files. As shown below, please revert back to original spacing except in the file you add the loading feature.
> 
> image

Sure

**Comment by stephin007** [comment]
Please resolve the conflicts!

**Pull request closed without merging**
