### PR TITLE
Added a loading component - Feat/issue 97

### PR DESCRIPTION
**Pull request by afif1400**
### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master**
- [x] Make sure no conflicts are present in the code, if so please resolve it(_Tip: Always fetch upstream_)
- [x] Your Commit messages should make sense.
- [x] Don't push your package.lock.json as this project uses yarn.lock already.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Describe your changes

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces a new feature of the loading component while fetching the data.

- **What is the current behavior?** (You can also link to an open issue here)
There is no indication to the user if the results are being fetched: issue #97 

- **What is the new behavior (if this is a feature change)?**
The new behavior is that there is a circular progress bar displayed if the results of the data are being fetched.

- **Does this PR introduce a breaking change?** (i.e changes that may require users to update/refactor existing instances of the application)
This feature does not introduce a breaking change.

- **Other Information**:

❤️ Thank you!

### CODE REVIEW

**Comment by stephin007** [comment]
@afif1400 still there are conflicts, PLease resolve it

but be careful, **PLEASE COMPARE CAREFULLY DONT REMOVE ANY EXISTING FUCNTIONALITY FROM THE DEFAULT BRANCH**

Just add your changes such that nothing else is not disturbed and your functionality works.

**Comment by afif1400** [comment]
Have resolved the conflicts

**Comment by stephin007** [comment]
@Justinnn07 can you review this assigning you

**Comment by Justinnn07** [comment]
> @Justinnn07 can you review this assigning you

Sure!

**Comment by stephin007** [comment]
@afif1400 saw the below error while deploying please fix this by using "===" wherever needed


image

**Review by Justinnn07 — APPROVED** [review]
Nice work! 🚀 @afif1400

**Comment by afif1400** [comment]
> Nice work! 🚀 @afif1400

@Justinnn07 thanks 😀

**Pull request merged**
