### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Ciggzy1312**
Added a request to fork and start repository
Added Production , Staging and New demo UI links
Added how to setup the project in local environment

### CODE REVIEW

**Comment by stephin007** [comment]
@Ciggzy1312 change your base branch to NEW-UI please

**Comment by Ciggzy1312** [comment]
> @Ciggzy1312 change your base branch to NEW-UI please

I don't know but I am facing some issues in changing the branch
Can you not merge this update README branch with master?

**Comment by stephin007** [comment]
No i cannot, we follow the flow of NEW-UI --> staging --> master.


If you could raise another PR and change the base to NEW-UI. That should do the work!

**Comment by stephin007** [comment]
Closing this as this is already done here https://github.com/stephin007/Cowin-Vaccine-Availablity-Checker/pull/93 and merged to staging and master. 

@Ciggzy1312 if you still want to contribute please check other issues or update the existing readme.md

Much Appreciated 
Thanks 🤝

**Pull request closed without merging**
