### PR TITLE
About Page Revamp

### PR DESCRIPTION
**Pull request by stephin007**
> 🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master**
- [x] Make sure no conflicts are present in the code, if so please resolve it(_Tip: Always fetch upstream_)
- [x] Your Commit messages should make sense.
- [x] Don't push your package.lock.json as this project uses yarn.lock already.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Describe your changes

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Enhancement 

- **What is the current behavior?** (You can also link to an open issue here).
About Page was empty earlier with very less information

- **What is the new behavior (if this is a feature change)?**
- Added list of contributors, right now this PR is in progress , will add proper information of the app in  the about page.

### NOTE FOR THE REVIEWER
This PR is
- not yet dark mode compatible
- not mobile responsive.
- incomplete, will add more information

- **Does this PR introduce a breaking change?** (i.e changes that may require users to update/refactor existing istances of the application)
Nil, No packages were added only 2 files were changed which are :
- About.js
- about.css

- **Other Information**:
NONE

❤️ Thank you!

### CODE REVIEW

**Comment by stephin007** [comment]
hey @Justinnn07 , this PR has the initial look of the about Page, please go through commits and let me know if there is anything i need to change.

**Comment by Justinnn07** [comment]
> hey @Justinnn07 , this PR has the initial look of the about Page, please go through commits and let me know if there is anything i need to change.

sure @stephin007

**Comment by Justinnn07** [comment]
image

@stephin007  This contributors list isn't mobile responsive, is it fine for now?

**Comment by stephin007** [comment]
Please read my PR DESCRIPTION @Justinnn07

**Comment by Justinnn07** [comment]
> Please read my PR DESCRIPTION @Justinnn07

sorry @stephin007 , mah bad , rest changes looks good!

**Review by Justinnn07 — APPROVED** [review]
LGTM! 🔥 @stephin007

**Pull request merged**
