### PR TITLE
added conflicts workflow 

### PR DESCRIPTION
**Pull request by Justinnn07**
> 🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

### Please check if the PR fulfills these requirements

- [x] Make sure you are requesting to **NEW-UI**. Don't request other protected Branches like **staging/master**
- [x] Make sure no conflicts are present in the code, if so please resolve it(_Tip: Always fetch upstream_)
- [x] Your Commit messages should make sense.
- [x] Don't push your package.lock.json as this project uses yarn.lock already.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Describe your changes

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- docs update 

- **What is the new behavior (if this is a feature change)?**
- added a new workflow

- **Does this PR introduce a breaking change?** (i.e changes that may require users to update/refactor existing istances of the application)
- NULL

- **Other Information**:

❤️ Thank you!

### CODE REVIEW

**Comment by stephin007** [comment]
@Justinnn07 Why are there 2 branches? will this check only work for staging and NEW-UI branch?

**Comment by Justinnn07** [comment]
> @Justinnn07 Why are there 2 branches? will this check only work for staging and NEW-UI branch?

Yes, This will work only while raising a New PR ..

**Comment by stephin007** [comment]
Can we add the `staging` branch for conflict check as right now,it has only `master` and `NEW-UI`  !

**Comment by Justinnn07** [comment]
> @Justinnn07
> Can we add the `staging` branch for conflict check as right now,it has only `master` and `NEW-UI` !

sure

**Comment by stephin007** [comment]
@Justinnn07 why is the check is the failing?? 😆 , i dont see any conflicts!

**Comment by stephin007** [comment]
it requires a label i guess, let me add that as well @Justinnn07

**Comment by stephin007** [comment]
@Justinnn07 whenever this conflicts-bot runs successfully will this create a comment? or will it show the comment only when the checks are failing?

**Comment by Justinnn07** [comment]
> @Justinnn07 whenever this conflicts-bot runs successfully will this create a comment? or will it show the comment only when the checks are failing?

When checks are failing , it will show the comment

**Review by stephin007 — APPROVED** [review]
LGTM, lets hope this works

**Pull request merged**
